# Generated by Django 3.2 on 2021-04-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=100)),
            ],
        ),
    ]
