# Generated by Django 3.2 on 2021-04-20 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radio',
            name='logo',
        ),
    ]
